user = User.create(
  name: 'test',
  email: 'test@example.com',
  password: 'password123',
  password_confirmation: 'password123'
  )

user_id = 1

@data1 = {
  first_name: "松本",
  last_name: "一馬",
  first_name_kana: "マツモト",
  last_name_kana: "カズマ",
  gender_id: 1,
  visit1_id: 1,
  visit2_id: 0,
  description: "趣味：映画鑑賞",
  user_id: user_id,
  adl_id: 1,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 4,
  remark_bath: "長風呂",
  drink_type_id: 1,
  thickness_id: 2,
  warm: 1,
  diabetes: 1,
  remark_drink: ""
}

@data2 = {
  first_name: "松下",
  last_name: "寛人",
  first_name_kana: "マツシタ",
  last_name_kana: "ヒロト",
  gender_id: 1,
  visit1_id: 1,
  visit2_id: 2,
  description: "趣味：園芸",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 2,
  infection_id: 1,
  timing_id: 4,
  remark_bath: "",
  drink_type_id: 2,
  thickness_id: 2,
  warm: 1,
  diabetes: 0,
  remark_drink: ""
}

@data3 = {
  first_name: "森田",
  last_name: "光一",
  first_name_kana: "モリタ",
  last_name_kana: "コウイチ",
  gender_id: 1,
  visit1_id: 1,
  visit2_id: 3,
  description: "趣味：読書",
  user_id: user_id,
  adl_id: 3,
  bathing_id: 3,
  infection_id: 2,
  timing_id: 5,
  remark_bath: "短時間浴",
  drink_type_id: 3,
  thickness_id: 2,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data4 = {
  first_name: "西本",
  last_name: "晃",
  first_name_kana: "ニシモト",
  last_name_kana: "アキラ",
  gender_id: 1,
  visit1_id: 1,
  visit2_id: 4,
  description: "趣味：美術鑑賞",
  user_id: user_id,
  adl_id: 1,
  bathing_id: 1,
  infection_id: 3,
  timing_id: 5,
  remark_bath: "",
  drink_type_id: 4,
  thickness_id: 2,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data5 = {
  first_name: "中谷",
  last_name: "真央",
  first_name_kana: "ナカタニ",
  last_name_kana: "マオ",
  gender_id: 2,
  visit1_id: 1,
  visit2_id: 5,
  description: "遊園地が好き",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 2,
  infection_id: 4,
  timing_id: 5,
  remark_bath: "",
  drink_type_id: 5,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data6 = {
  first_name: "杉山",
  last_name: "飛鳥",
  first_name_kana: "スギヤマ",
  last_name_kana: "アスカ",
  gender_id: 2,
  visit1_id: 1,
  visit2_id: 6,
  description: "動物が好き",
  user_id: user_id,
  adl_id: 4,
  bathing_id: 3,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 6,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data7 = {
  first_name: "古谷",
  last_name: "沙和",
  first_name_kana: "フルタニ",
  last_name_kana: "サワ",
  gender_id: 2,
  visit1_id: 1,
  visit2_id: 7,
  description: "水族館が好き",
  user_id: user_id,
  adl_id: 1,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 7,
  thickness_id: 1,
  warm: 0,
  diabetes: 1,
  remark_drink: ""
}

@data8 = {
  first_name: "村井",
  last_name: "秀次",
  first_name_kana: "ムライ",
  last_name_kana: "ヒデジ",
  gender_id: 1,
  visit1_id: 2,
  visit2_id: 0,
  description: "カラオケが好き",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 2,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 8,
  thickness_id: 1,
  warm: 1,
  diabetes: 1,
  remark_drink: ""
}

@data9 = {
  first_name: "吉田",
  last_name: "薫",
  first_name_kana: "ヨシダ",
  last_name_kana: "カオル",
  gender_id: 1,
  visit1_id: 2,
  visit2_id: 3,
  description: "音楽が好き",
  user_id: user_id,
  adl_id: 3,
  bathing_id: 3,
  infection_id: 2,
  timing_id: 5,
  remark_bath: "",
  drink_type_id: 1,
  thickness_id: 2,
  warm: 1,
  diabetes: 1,
  remark_drink: ""
}

@data10 = {
  first_name: "尾崎",
  last_name: "康太",
  first_name_kana: "オザキ",
  last_name_kana: "コウタ",
  gender_id: 1,
  visit1_id: 2,
  visit2_id: 4,
  description: "音楽が好き",
  user_id: user_id,
  adl_id: 1,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 2,
  thickness_id: 2,
  warm: 1,
  diabetes: 0,
  remark_drink: ""
}

@data11 = {
  first_name: "江越",
  last_name: "楓",
  first_name_kana: "エゴシ",
  last_name_kana: "カエデ",
  gender_id: 2,
  visit1_id: 2,
  visit2_id: 5,
  description: "演歌が好き",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 2,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 3,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data12 = {
  first_name: "山本",
  last_name: "摩耶",
  first_name_kana: "ヤマモト",
  last_name_kana: "マヤ",
  gender_id: 2,
  visit1_id: 2,
  visit2_id: 6,
  description: "演劇が好き",
  user_id: user_id,
  adl_id: 3,
  bathing_id: 3,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "女性対応",
  drink_type_id: 4,
  thickness_id: 3,
  warm: 0,
  diabetes: 0,
  remark_drink: "少量で良い"
}

@data13 = {
  first_name: "太田",
  last_name: "舞",
  first_name_kana: "オオタ",
  last_name_kana: "マイ",
  gender_id: 2,
  visit1_id: 2,
  visit2_id: 7,
  description: "カメラが好き",
  user_id: user_id,
  adl_id: 1,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "女性対応",
  drink_type_id: 5,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data14 = {
  first_name: "大石",
  last_name: "伊津子",
  first_name_kana: "オオイシ",
  last_name_kana: "イツコ",
  gender_id: 2,
  visit1_id: 3,
  visit2_id: 0,
  description: "旅行が好き",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 2,
  infection_id: 3,
  timing_id: 5,
  remark_bath: "",
  drink_type_id: 6,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data15 = {
  first_name: "西村",
  last_name: "樹",
  first_name_kana: "ニシムラ",
  last_name_kana: "イツキ",
  gender_id: 1,
  visit1_id: 3,
  visit2_id: 4,
  description: "日曜大工が趣味",
  user_id: user_id,
  adl_id: 4,
  bathing_id: 3,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 7,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: "本人用スプーンをつける"
}

@data16 = {
  first_name: "野村",
  last_name: "和子",
  first_name_kana: "ノムラ",
  last_name_kana: "カズコ",
  gender_id: 2,
  visit1_id: 3,
  visit2_id: 5,
  description: "料理が趣味",
  user_id: user_id,
  adl_id: 1,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 8,
  thickness_id: 1,
  warm: 1,
  diabetes: 1,
  remark_drink: ""
}

@data17 = {
  first_name: "安達",
  last_name: "拓也",
  first_name_kana: "アダチ",
  last_name_kana: "タクヤ",
  gender_id: 1,
  visit1_id: 3,
  visit2_id: 6,
  description: "料理が趣味",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 2,
  infection_id: 4,
  timing_id: 5,
  remark_bath: "",
  drink_type_id: 1,
  thickness_id: 1,
  warm: 1,
  diabetes: 0,
  remark_drink: ""
}

@data18 = {
  first_name: "長谷川",
  last_name: "優香",
  first_name_kana: "ハセガワ",
  last_name_kana: "ユウカ",
  gender_id: 2,
  visit1_id: 3,
  visit2_id: 7,
  description: "裁縫が得意",
  user_id: user_id,
  adl_id: 3,
  bathing_id: 3,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 2,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data19 = {
  first_name: "川野",
  last_name: "公一",
  first_name_kana: "カワノ",
  last_name_kana: "コウイチ",
  gender_id: 1,
  visit1_id: 4,
  visit2_id: 0,
  description: "元大工",
  user_id: user_id,
  adl_id: 1,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 3,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data20 = {
  first_name: "山下",
  last_name: "エヨ",
  first_name_kana: "ヤマシタ",
  last_name_kana: "エヨ",
  gender_id: 2,
  visit1_id: 4,
  visit2_id: 5,
  description: "職人の妻",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 2,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 4,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data21 = {
  first_name: "神谷",
  last_name: "武雄",
  first_name_kana: "カミヤ",
  last_name_kana: "タケオ",
  gender_id: 1,
  visit1_id: 4,
  visit2_id: 6,
  description: "盆栽が趣味",
  user_id: user_id,
  adl_id: 4,
  bathing_id: 3,
  infection_id: 5,
  timing_id: 5,
  remark_bath: "",
  drink_type_id: 5,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: "自助スプーンをつける"
}

@data22 = {
  first_name: "入江",
  last_name: "美香",
  first_name_kana: "イリエ",
  last_name_kana: "ミカ",
  gender_id: 2,
  visit1_id: 4,
  visit2_id: 7,
  description: "漬物作りが上手",
  user_id: user_id,
  adl_id: 1,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 2,
  remark_bath: "",
  drink_type_id: 6,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data23 = {
  first_name: "小松",
  last_name: "信繁",
  first_name_kana: "コマツ",
  last_name_kana: "ノブシゲ",
  gender_id: 1,
  visit1_id: 5,
  visit2_id: 0,
  description: "自営業",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 2,
  infection_id: 2,
  timing_id: 5,
  remark_bath: "",
  drink_type_id: 7,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data24 = {
  first_name: "吉野",
  last_name: "聖",
  first_name_kana: "ヨシノ",
  last_name_kana: "ヒジリ",
  gender_id: 2,
  visit1_id: 5,
  visit2_id: 6,
  description: "お菓子屋",
  user_id: user_id,
  adl_id: 3,
  bathing_id: 3,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 8,
  thickness_id: 1,
  warm: 0,
  diabetes: 1,
  remark_drink: ""
}

@data25 = {
  first_name: "阿達",
  last_name: "作次郎",
  first_name_kana: "アダチ",
  last_name_kana: "サクジロウ",
  gender_id: 1,
  visit1_id: 5,
  visit2_id: 7,
  description: "お菓子屋",
  user_id: user_id,
  adl_id: 1,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 1,
  thickness_id: 3,
  warm: 1,
  diabetes: 1,
  remark_drink: ""
}

@data26 = {
  first_name: "古谷",
  last_name: "俊美",
  first_name_kana: "フルタニ",
  last_name_kana: "トシミ",
  gender_id: 2,
  visit1_id: 6,
  visit2_id: 0,
  description: "小柄",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 2,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 2,
  thickness_id: 2,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data27 = {
  first_name: "藤岡",
  last_name: "忍",
  first_name_kana: "フジオカ",
  last_name_kana: "シノブ",
  gender_id: 1,
  visit1_id: 6,
  visit2_id: 7,
  description: "力自慢だった",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 2,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 3,
  thickness_id: 2,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data28 = {
  first_name: "柳沢",
  last_name: "悦",
  first_name_kana: "ヤナギサワ",
  last_name_kana: "エツ",
  gender_id: 2,
  visit1_id: 7,
  visit2_id: 0,
  description: "日向ぼっこが趣味",
  user_id: user_id,
  adl_id: 4,
  bathing_id: 3,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "長風呂",
  drink_type_id: 4,
  thickness_id: 1,
  warm: 1,
  diabetes: 0,
  remark_drink: ""
}

@data29 = {
  first_name: "浅野",
  last_name: "裕樹",
  first_name_kana: "アサノ",
  last_name_kana: "ユウキ",
  gender_id: 1,
  visit1_id: 4,
  visit2_id: 7,
  description: "歌謡曲が好き",
  user_id: user_id,
  adl_id: 4,
  bathing_id: 3,
  infection_id: 1,
  timing_id: 1,
  remark_bath: "風呂嫌い",
  drink_type_id: 1,
  thickness_id: 1,
  warm: 1,
  diabetes: 0,
  remark_drink: ""
}

@data30 = {
  first_name: "石田",
  last_name: "彩花",
  first_name_kana: "イシダ",
  last_name_kana: "アヤカ",
  gender_id: 2,
  visit1_id: 2,
  visit2_id: 7,
  description: "旅行が趣味だった",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 2,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "女性対応",
  drink_type_id: 1,
  thickness_id: 1,
  warm: 0,
  diabetes: 1,
  remark_drink: ""
}

@data31 = {
  first_name: "山岸",
  last_name: "博久",
  first_name_kana: "ヤマギシ",
  last_name_kana: "ヒロヒサ",
  gender_id: 1,
  visit1_id: 1,
  visit2_id: 0,
  description: "パソコンが得意",
  user_id: user_id,
  adl_id: 1,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 8,
  thickness_id: 1,
  warm: 1,
  diabetes: 0,
  remark_drink: ""
}

@data32 = {
  first_name: "中谷",
  last_name: "正雄",
  first_name_kana: "ナカタニ",
  last_name_kana: "マサオ",
  gender_id: 1,
  visit1_id: 1,
  visit2_id: 2,
  description: "ボランティアが趣味",
  user_id: user_id,
  adl_id: 3,
  bathing_id: 3,
  infection_id: 1,
  timing_id: 2,
  remark_bath: "",
  drink_type_id: 1,
  thickness_id: 2,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data33 = {
  first_name: "堀江",
  last_name: "武",
  first_name_kana: "ホリエ",
  last_name_kana: "タケシ",
  gender_id: 1,
  visit1_id: 1,
  visit2_id: 3,
  description: "昔先生をしていた",
  user_id: user_id,
  adl_id: 3,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 2,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data34 = {
  first_name: "相馬",
  last_name: "克樹",
  first_name_kana: "ソウマ",
  last_name_kana: "カツキ",
  gender_id: 1,
  visit1_id: 1,
  visit2_id: 4,
  description: "習字が得意",
  user_id: user_id,
  adl_id: 1,
  bathing_id: 2,
  infection_id: 3,
  timing_id: 5,
  remark_bath: "",
  drink_type_id: 3,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data35 = {
  first_name: "山中",
  last_name: "優香",
  first_name_kana: "ヤマナカ",
  last_name_kana: "ユウカ",
  gender_id: 2,
  visit1_id: 1,
  visit2_id: 5,
  description: "絵が上手",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 2,
  infection_id: 4,
  timing_id: 5,
  remark_bath: "",
  drink_type_id: 4,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data36 = {
  first_name: "蒲田",
  last_name: "静江",
  first_name_kana: "カマタ",
  last_name_kana: "シズエ",
  gender_id: 2,
  visit1_id: 1,
  visit2_id: 6,
  description: "絵手紙が好き",
  user_id: user_id,
  adl_id: 4,
  bathing_id: 3,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 5,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data37 = {
  first_name: "安藤",
  last_name: "弘子",
  first_name_kana: "アンドウ",
  last_name_kana: "ヒロコ",
  gender_id: 2,
  visit1_id: 1,
  visit2_id: 7,
  description: "俳句が得意",
  user_id: user_id,
  adl_id: 1,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 6,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data38 = {
  first_name: "松山",
  last_name: "元",
  first_name_kana: "マツヤマ",
  last_name_kana: "ゲン",
  gender_id: 1,
  visit1_id: 2,
  visit2_id: 0,
  description: "お菓子が好き",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 7,
  thickness_id: 1,
  warm: 0,
  diabetes: 1,
  remark_drink: ""
}

@data39 = {
  first_name: "田中",
  last_name: "良雄",
  first_name_kana: "タナカ",
  last_name_kana: "ヨシオ",
  gender_id: 1,
  visit1_id: 2,
  visit2_id: 3,
  description: "歌が好き",
  user_id: user_id,
  adl_id: 1,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 1,
  remark_bath: "",
  drink_type_id: 1,
  thickness_id: 2,
  warm: 1,
  diabetes: 0,
  remark_drink: ""
}

@data40 = {
  first_name: "小野",
  last_name: "圭介",
  first_name_kana: "オノ",
  last_name_kana: "ケイスケ",
  gender_id: 1,
  visit1_id: 2,
  visit2_id: 4,
  description: "音楽が好き",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 2,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 2,
  thickness_id: 2,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data41 = {
  first_name: "森岡",
  last_name: "美恵",
  first_name_kana: "モリオカ",
  last_name_kana: "ミエ",
  gender_id: 2,
  visit1_id: 2,
  visit2_id: 5,
  description: "生花教室に通っていた",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 1,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data42 = {
  first_name: "中野",
  last_name: "瞳",
  first_name_kana: "ナカノ",
  last_name_kana: "ヒトミ",
  gender_id: 2,
  visit1_id: 2,
  visit2_id: 6,
  description: "ブリザーブドフラワー作りが趣味",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "女性対応",
  drink_type_id: 1,
  thickness_id: 3,
  warm: 0,
  diabetes: 1,
  remark_drink: ""
}

@data43 = {
  first_name: "桜井",
  last_name: "紀子",
  first_name_kana: "サクライ",
  last_name_kana: "ノリコ",
  gender_id: 2,
  visit1_id: 2,
  visit2_id: 7,
  description: "算盤が得意",
  user_id: user_id,
  adl_id: 3,
  bathing_id: 3,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "女性対応",
  drink_type_id: 1,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data44 = {
  first_name: "市川",
  last_name: "敏子",
  first_name_kana: "イチカワ",
  last_name_kana: "トシコ",
  gender_id: 2,
  visit1_id: 3,
  visit2_id: 0,
  description: "パズルが好き",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 4,
  remark_bath: "",
  drink_type_id: 2,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data45 = {
  first_name: "広田",
  last_name: "和樹",
  first_name_kana: "ヒロタ",
  last_name_kana: "カズキ",
  gender_id: 1,
  visit1_id: 3,
  visit2_id: 4,
  description: "間違い探しが好き",
  user_id: user_id,
  adl_id: 4,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 7,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data46 = {
  first_name: "佐藤",
  last_name: "ナナ",
  first_name_kana: "サトウ",
  last_name_kana: "ナナ",
  gender_id: 2,
  visit1_id: 3,
  visit2_id: 5,
  description: "ヨガが趣味",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 2,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 7,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data47 = {
  first_name: "坂本",
  last_name: "冬樹",
  first_name_kana: "サカモト",
  last_name_kana: "フユキ",
  gender_id: 1,
  visit1_id: 3,
  visit2_id: 6,
  description: "昼寝が好き",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 2,
  remark_bath: "",
  drink_type_id: 1,
  thickness_id: 1,
  warm: 1,
  diabetes: 0,
  remark_drink: ""
}

@data48 = {
  first_name: "石川",
  last_name: "知世",
  first_name_kana: "イシカワ",
  last_name_kana: "トモヨ",
  gender_id: 2,
  visit1_id: 3,
  visit2_id: 7,
  description: "パン作りが得意",
  user_id: user_id,
  adl_id: 3,
  bathing_id: 3,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 1,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data49 = {
  first_name: "鉢元",
  last_name: "牧夫",
  first_name_kana: "ハチモト",
  last_name_kana: "マキオ",
  gender_id: 1,
  visit1_id: 4,
  visit2_id: 0,
  description: "県庁に勤めていた",
  user_id: user_id,
  adl_id: 1,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 3,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data50 = {
  first_name: "北川",
  last_name: "恵子",
  first_name_kana: "キタガワ",
  last_name_kana: "ケイコ",
  gender_id: 2,
  visit1_id: 4,
  visit2_id: 5,
  description: "少食",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 3,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: "ストローをつける"
}

@data51 = {
  first_name: "大平",
  last_name: "良",
  first_name_kana: "オオダイラ",
  last_name_kana: "リョウ",
  gender_id: 1,
  visit1_id: 4,
  visit2_id: 6,
  description: "錦鯉が趣味",
  user_id: user_id,
  adl_id: 4,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 8,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data52 = {
  first_name: "坂口",
  last_name: "ハル",
  first_name_kana: "サカグチ",
  last_name_kana: "ハル",
  gender_id: 2,
  visit1_id: 4,
  visit2_id: 7,
  description: "味噌作りが上手",
  user_id: user_id,
  adl_id: 1,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 2,
  remark_bath: "",
  drink_type_id: 4,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: "マイコップに注ぐ"
}

@data53 = {
  first_name: "浜野",
  last_name: "明典",
  first_name_kana: "ハマノ",
  last_name_kana: "アキノリ",
  gender_id: 1,
  visit1_id: 5,
  visit2_id: 0,
  description: "話がうまい",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 5,
  remark_bath: "",
  drink_type_id: 7,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data54 = {
  first_name: "大代",
  last_name: "ナツ",
  first_name_kana: "オオシロ",
  last_name_kana: "ナツ",
  gender_id: 2,
  visit1_id: 5,
  visit2_id: 6,
  description: "駄菓子屋を営んでいた",
  user_id: user_id,
  adl_id: 3,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 7,
  thickness_id: 1,
  warm: 0,
  diabetes: 1,
  remark_drink: ""
}

@data55 = {
  first_name: "青木",
  last_name: "太郎",
  first_name_kana: "アオキ",
  last_name_kana: "タロウ",
  gender_id: 1,
  visit1_id: 5,
  visit2_id: 7,
  description: "農家をしていた",
  user_id: user_id,
  adl_id: 1,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 1,
  thickness_id: 2,
  warm: 1,
  diabetes: 1,
  remark_drink: ""
}

@data56 = {
  first_name: "中野",
  last_name: "アキ",
  first_name_kana: "ナカノ",
  last_name_kana: "アキ",
  gender_id: 2,
  visit1_id: 6,
  visit2_id: 0,
  description: "大柄",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 2,
  thickness_id: 2,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data57 = {
  first_name: "清水",
  last_name: "正光",
  first_name_kana: "シミズ",
  last_name_kana: "マサミツ",
  gender_id: 1,
  visit1_id: 6,
  visit2_id: 7,
  description: "元力士",
  user_id: user_id,
  adl_id: 3,
  bathing_id: 3,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 3,
  thickness_id: 2,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data58 = {
  first_name: "服部",
  last_name: "フユ",
  first_name_kana: "ハットリ",
  last_name_kana: "フユ",
  gender_id: 2,
  visit1_id: 7,
  visit2_id: 0,
  description: "世間話が好き",
  user_id: user_id,
  adl_id: 1,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "リンス持参",
  drink_type_id: 5,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data59 = {
  first_name: "清水",
  last_name: "良雄",
  first_name_kana: "シミズ",
  last_name_kana: "ヨシオ",
  gender_id: 1,
  visit1_id: 1,
  visit2_id: 6,
  description: "ビジネスマンだった",
  user_id: user_id,
  adl_id: 1,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "湿疹に注意",
  drink_type_id: 7,
  thickness_id: 1,
  warm: 0,
  diabetes: 1,
  remark_drink: ""
}

@data60 = {
  first_name: "原口",
  last_name: "夏帆",
  first_name_kana: "ハラグチ",
  last_name_kana: "カホ",
  gender_id: 2,
  visit1_id: 3,
  visit2_id: 5,
  description: "海外に住んでいた",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 3,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "女性対応",
  drink_type_id: 1,
  thickness_id: 1,
  warm: 1,
  diabetes: 0,
  remark_drink: ""
}

@data61 = {
  first_name: "岩本",
  last_name: "瑛太",
  first_name_kana: "イワモト",
  last_name_kana: "エイタ",
  gender_id: 1,
  visit1_id: 2,
  visit2_id: 0,
  description: "ニンジンが好き",
  user_id: user_id,
  adl_id: 1,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 8,
  thickness_id: 1,
  warm: 1,
  diabetes: 0,
  remark_drink: ""
}

@data62 = {
  first_name: "下村",
  last_name: "トヨ",
  first_name_kana: "シモムラ",
  last_name_kana: "トヨ",
  gender_id: 2,
  visit1_id: 1,
  visit2_id: 2,
  description: "ボランティアが趣味",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 2,
  infection_id: 1,
  timing_id: 2,
  remark_bath: "",
  drink_type_id: 6,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data63 = {
  first_name: "相沢",
  last_name: "幸平",
  first_name_kana: "アイザワ",
  last_name_kana: "コウヘイ",
  gender_id: 1,
  visit1_id: 1,
  visit2_id: 3,
  description: "昔先生をしていた",
  user_id: user_id,
  adl_id: 3,
  bathing_id: 2,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 4,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data64 = {
  first_name: "横井",
  last_name: "ツヤ",
  first_name_kana: "ヨコイ",
  last_name_kana: "ツヤ",
  gender_id: 2,
  visit1_id: 1,
  visit2_id: 4,
  description: "ピザが好き",
  user_id: user_id,
  adl_id: 3,
  bathing_id: 3,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 5,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data65 = {
  first_name: "土屋",
  last_name: "博",
  first_name_kana: "ツチヤ",
  last_name_kana: "ヒロシ",
  gender_id: 1,
  visit1_id: 1,
  visit2_id: 5,
  description: "砂絵が上手",
  user_id: user_id,
  adl_id: 3,
  bathing_id: 3,
  infection_id: 4,
  timing_id: 5,
  remark_bath: "",
  drink_type_id: 2,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data66 = {
  first_name: "高瀬",
  last_name: "トミ",
  first_name_kana: "タカセ",
  last_name_kana: "トミ",
  gender_id: 2,
  visit1_id: 1,
  visit2_id: 6,
  description: "絵葉書が好き",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 2,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 4,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data67 = {
  first_name: "栗原",
  last_name: "誠",
  first_name_kana: "クリハラ",
  last_name_kana: "マコト",
  gender_id: 1,
  visit1_id: 1,
  visit2_id: 7,
  description: "俳句が得意",
  user_id: user_id,
  adl_id: 1,
  bathing_id: 2,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 2,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data68 = {
  first_name: "浜田",
  last_name: "良雄",
  first_name_kana: "ハマダ",
  last_name_kana: "ヨシオ",
  gender_id: 1,
  visit1_id: 2,
  visit2_id: 0,
  description: "お菓子が好き",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 3,
  thickness_id: 1,
  warm: 1,
  diabetes: 0,
  remark_drink: ""
}

@data69 = {
  first_name: "山岡",
  last_name: "慶次",
  first_name_kana: "ヤマオカ",
  last_name_kana: "ケイジ",
  gender_id: 1,
  visit1_id: 2,
  visit2_id: 3,
  description: "踊りが好き",
  user_id: user_id,
  adl_id: 1,
  bathing_id: 2,
  infection_id: 1,
  timing_id: 1,
  remark_bath: "",
  drink_type_id: 5,
  thickness_id: 2,
  warm: 1,
  diabetes: 0,
  remark_drink: ""
}

@data70 = {
  first_name: "野崎",
  last_name: "トモ",
  first_name_kana: "ノザキ",
  last_name_kana: "トモ",
  gender_id: 2,
  visit1_id: 2,
  visit2_id: 4,
  description: "なすが好き",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 3,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 6,
  thickness_id: 2,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data71 = {
  first_name: "中村",
  last_name: "哲",
  first_name_kana: "ナカムラ",
  last_name_kana: "テツ",
  gender_id: 1,
  visit1_id: 2,
  visit2_id: 5,
  description: "生花教室の先生だった",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 3,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 6,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data72 = {
  first_name: "瀬戸",
  last_name: "スイ",
  first_name_kana: "セト",
  last_name_kana: "スイ",
  gender_id: 2,
  visit1_id: 2,
  visit2_id: 6,
  description: "花農家だった",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 2,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 6,
  thickness_id: 3,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data73 = {
  first_name: "青柳",
  last_name: "大",
  first_name_kana: "アオヤギ",
  last_name_kana: "ダイ",
  gender_id: 1,
  visit1_id: 2,
  visit2_id: 7,
  description: "手先が器用",
  user_id: user_id,
  adl_id: 3,
  bathing_id: 3,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 8,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data74 = {
  first_name: "中本",
  last_name: "ツネ",
  first_name_kana: "ナカモト",
  last_name_kana: "ツネ",
  gender_id: 2,
  visit1_id: 3,
  visit2_id: 0,
  description: "パズルが好き",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 4,
  remark_bath: "",
  drink_type_id: 6,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data75 = {
  first_name: "高野",
  last_name: "キク",
  first_name_kana: "タカノ",
  last_name_kana: "キク",
  gender_id: 2,
  visit1_id: 3,
  visit2_id: 4,
  description: "脳トレが好き",
  user_id: user_id,
  adl_id: 4,
  bathing_id: 3,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 7,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data76 = {
  first_name: "大橋",
  last_name: "弥太郎",
  first_name_kana: "オオハシ",
  last_name_kana: "ヤタロウ",
  gender_id: 1,
  visit1_id: 3,
  visit2_id: 5,
  description: "ラジオ体操が趣味",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 3,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 6,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data77 = {
  first_name: "名古屋",
  last_name: "寿喜",
  first_name_kana: "ナゴヤ",
  last_name_kana: "カズヨシ",
  gender_id: 1,
  visit1_id: 3,
  visit2_id: 6,
  description: "筋トレが趣味",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 2,
  infection_id: 1,
  timing_id: 2,
  remark_bath: "",
  drink_type_id: 4,
  thickness_id: 1,
  warm: 1,
  diabetes: 0,
  remark_drink: ""
}

@data78 = {
  first_name: "細川",
  last_name: "文雄",
  first_name_kana: "ホソカワ",
  last_name_kana: "フミオ",
  gender_id: 1,
  visit1_id: 3,
  visit2_id: 7,
  description: "パン職人だった",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 2,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 2,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data79 = {
  first_name: "清水",
  last_name: "アキエ",
  first_name_kana: "シミズ",
  last_name_kana: "アキエ",
  gender_id: 2,
  visit1_id: 4,
  visit2_id: 0,
  description: "市役所に勤めていた",
  user_id: user_id,
  adl_id: 3,
  bathing_id: 3,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 3,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data80 = {
  first_name: "難波",
  last_name: "サチ",
  first_name_kana: "ナンバ",
  last_name_kana: "サチ",
  gender_id: 2,
  visit1_id: 4,
  visit2_id: 5,
  description: "少食",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 3,
  infection_id: 2,
  timing_id: 5,
  remark_bath: "心臓が悪い",
  drink_type_id: 6,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data81 = {
  first_name: "本田",
  last_name: "トシ",
  first_name_kana: "ホンダ",
  last_name_kana: "トシ",
  gender_id: 2,
  visit1_id: 4,
  visit2_id: 6,
  description: "草抜きが趣味",
  user_id: user_id,
  adl_id: 4,
  bathing_id: 2,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 1,
  thickness_id: 1,
  warm: 1,
  diabetes: 0,
  remark_drink: ""
}

@data82 = {
  first_name: "村松",
  last_name: "ウミ",
  first_name_kana: "ムラマツ",
  last_name_kana: "ウミ",
  gender_id: 2,
  visit1_id: 4,
  visit2_id: 7,
  description: "白菜がすき",
  user_id: user_id,
  adl_id: 1,
  bathing_id: 2,
  infection_id: 1,
  timing_id: 2,
  remark_bath: "",
  drink_type_id: 2,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data83 = {
  first_name: "上田",
  last_name: "亘",
  first_name_kana: "ウエダ",
  last_name_kana: "ワタル",
  gender_id: 1,
  visit1_id: 5,
  visit2_id: 0,
  description: "人当たりがいい",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 2,
  infection_id: 1,
  timing_id: 5,
  remark_bath: "",
  drink_type_id: 2,
  thickness_id: 1,
  warm: 1,
  diabetes: 0,
  remark_drink: ""
}

@data84 = {
  first_name: "小倉",
  last_name: "良二",
  first_name_kana: "オグラ",
  last_name_kana: "リョウジ",
  gender_id: 1,
  visit1_id: 5,
  visit2_id: 6,
  description: "靴屋を営んでいた",
  user_id: user_id,
  adl_id: 3,
  bathing_id: 2,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 1,
  thickness_id: 1,
  warm: 0,
  diabetes: 1,
  remark_drink: "最後に提供する"
}

@data85 = {
  first_name: "渡邉",
  last_name: "久蔵",
  first_name_kana: "ワタナベ",
  last_name_kana: "キュウゾウ",
  gender_id: 1,
  visit1_id: 5,
  visit2_id: 7,
  description: "苺農家をしていた",
  user_id: user_id,
  adl_id: 1,
  bathing_id: 3,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 2,
  thickness_id: 2,
  warm: 1,
  diabetes: 0,
  remark_drink: ""
}

@data86 = {
  first_name: "北島",
  last_name: "フミノ",
  first_name_kana: "キタジマ",
  last_name_kana: "フミノ",
  gender_id: 2,
  visit1_id: 6,
  visit2_id: 0,
  description: "大柄",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 1,
  thickness_id: 3,
  warm: 0,
  diabetes: 1,
  remark_drink: ""
}

@data87 = {
  first_name: "新田",
  last_name: "富雄",
  first_name_kana: "ニッタ",
  last_name_kana: "トミオ",
  gender_id: 1,
  visit1_id: 6,
  visit2_id: 7,
  description: "ちゃんこ作りが趣味",
  user_id: user_id,
  adl_id: 3,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 6,
  thickness_id: 2,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data88 = {
  first_name: "臼井",
  last_name: "昭雄",
  first_name_kana: "ウスイ",
  last_name_kana: "アキオ",
  gender_id: 1,
  visit1_id: 7,
  visit2_id: 0,
  description: "世間話が好き",
  user_id: user_id,
  adl_id: 1,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 2,
  thickness_id: 2,
  warm: 1,
  diabetes: 0,
  remark_drink: ""
}

@data89 = {
  first_name: "三浦",
  last_name: "忠次",
  first_name_kana: "ミウラ",
  last_name_kana: "タダツグ",
  gender_id: 1,
  visit1_id: 1,
  visit2_id: 7,
  description: "銭湯で番頭をしていた",
  user_id: user_id,
  adl_id: 1,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 8,
  thickness_id: 1,
  warm: 1,
  diabetes: 0,
  remark_drink: ""
}

@data90 = {
  first_name: "園田",
  last_name: "巧",
  first_name_kana: "ソノダ",
  last_name_kana: "タクミ",
  gender_id: 1,
  visit1_id: 5,
  visit2_id: 6,
  description: "工事現場で働いていた",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 2,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 1,
  thickness_id: 1,
  warm: 1,
  diabetes: 0,
  remark_drink: ""
}

@data91 = {
  first_name: "大崎",
  last_name: "香",
  first_name_kana: "オオサキ",
  last_name_kana: "カオリ",
  gender_id: 2,
  visit1_id: 1,
  visit2_id: 4,
  description: "世間話が好き",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 1,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data92 = {
  first_name: "宮川",
  last_name: "小夜",
  first_name_kana: "ミヤガワ",
  last_name_kana: "サヨ",
  gender_id: 2,
  visit1_id: 1,
  visit2_id: 4,
  description: "寂しがり屋",
  user_id: user_id,
  adl_id: 2,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 1,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data93 = {
  first_name: "足立",
  last_name: "真子",
  first_name_kana: "アダチ",
  last_name_kana: "マサコ",
  gender_id: 2,
  visit1_id: 1,
  visit2_id: 4,
  description: "人と話すのが好き",
  user_id: user_id,
  adl_id: 1,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 1,
  thickness_id: 1,
  warm: 1,
  diabetes: 0,
  remark_drink: ""
}

@data94 = {
  first_name: "野田",
  last_name: "鈴子",
  first_name_kana: "ノダ",
  last_name_kana: "スズコ",
  gender_id: 2,
  visit1_id: 3,
  visit2_id: 0,
  description: "夏が好き",
  user_id: user_id,
  adl_id: 1,
  bathing_id: 2,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 3,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data95 = {
  first_name: "奥山",
  last_name: "佳子",
  first_name_kana: "オクヤマ",
  last_name_kana: "ヨシコ",
  gender_id: 2,
  visit1_id: 3,
  visit2_id: 0,
  description: "春が好き",
  user_id: user_id,
  adl_id: 1,
  bathing_id: 2,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 5,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data96 = {
  first_name: "山内",
  last_name: "静香",
  first_name_kana: "ヤマウチ",
  last_name_kana: "シズカ",
  gender_id: 2,
  visit1_id: 3,
  visit2_id: 7,
  description: "秋が好き",
  user_id: user_id,
  adl_id: 1,
  bathing_id: 2,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 8,
  thickness_id: 1,
  warm: 1,
  diabetes: 1,
  remark_drink: ""
}

@data97 = {
  first_name: "関口",
  last_name: "可奈",
  first_name_kana: "セキグチ",
  last_name_kana: "カナ",
  gender_id: 2,
  visit1_id: 2,
  visit2_id: 0,
  description: "冬が好き",
  user_id: user_id,
  adl_id: 1,
  bathing_id: 2,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 2,
  thickness_id: 1,
  warm: 1,
  diabetes: 0,
  remark_drink: ""
}

@data98 = {
  first_name: "中野",
  last_name: "浩美",
  first_name_kana: "ナカノ",
  last_name_kana: "ヒロミ",
  gender_id: 2,
  visit1_id: 2,
  visit2_id: 0,
  description: "キャベツ農家をしていた",
  user_id: user_id,
  adl_id: 1,
  bathing_id: 2,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 4,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data99 = {
  first_name: "田村",
  last_name: "宏",
  first_name_kana: "タムラ",
  last_name_kana: "ヒロシ",
  gender_id: 1,
  visit1_id: 5,
  visit2_id: 6,
  description: "祭りが好き",
  user_id: user_id,
  adl_id: 1,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 2,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}

@data100 = {
  first_name: "前川",
  last_name: "圭一",
  first_name_kana: "マエカワ",
  last_name_kana: "ケイイチ",
  gender_id: 1,
  visit1_id: 5,
  visit2_id: 6,
  description: "お好み焼きが好き",
  user_id: user_id,
  adl_id: 1,
  bathing_id: 1,
  infection_id: 1,
  timing_id: 3,
  remark_bath: "",
  drink_type_id: 2,
  thickness_id: 1,
  warm: 0,
  diabetes: 0,
  remark_drink: ""
}




@datas = [@data1, @data2, @data3, @data4, @data5, @data6, @data7, @data8, @data9, @data10, 
@data11, @data12, @data13, @data14, @data15, @data16, @data17, @data18, @data19, @data20,
@data21, @data22, @data23, @data24, @data25, @data26, @data27, @data28, @data29, @data30,
@data31, @data32, @data33, @data34, @data35, @data36, @data37, @data38, @data39, @data40,
@data41, @data42, @data43, @data44, @data45, @data46, @data47, @data48, @data49, @data50,
@data51, @data52, @data53, @data54, @data55, @data56, @data57, @data58, @data59, @data60,
@data61, @data62, @data63, @data64, @data65, @data66, @data67, @data68, @data69, @data70,
@data71, @data72, @data73, @data74, @data75, @data76, @data77, @data78, @data79, @data80,
@data81, @data82, @data83, @data84, @data85, @data86, @data87, @data88, @data89, @data90,
@data91, @data92, @data93, @data94, @data95, @data96, @data97, @data98, @data99, @data100,
]


@datas.each do |data|
  @guestdata = GuestData.new(data)
  @guestdata.save
end
